Add centralised build, test & deploy workflow for backend services
glimpse-protocol/workflows pull request #1
Opened 2022-01-24 17:17 UTC by samueldobbie

2022-01-25 11:06 UTC, tim-hm requested changes
Fantastic first iteration! As discussed a summary of next steps/changes:

- [ ] job structure
  
  1. code quality
  2. test & code coverage (tbc - kover)
  3. containerise (needs test)
  4. deploy XYZ (needs containerise, accepts region & cluster-name as env vars)

- [ ] can we set secrets globally for the workflow to be shared between jobs?

- [ ] success criteria
  - can i commit to dev and have it push the container?
  - can i trigger a deploy to alpha?

Heres an example of what I think this needs to look like when finished (and if possible!):

```yaml
name: service-lifecycle

on: push

secrets:
  GH_PAT: ${{ secrets.GH_PAT }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SONARQUBE_LOGIN_KEY: ${{ secrets.SONARQUBE_LOGIN_KEY }}

with:
  SERVICE_NAME: vault-attribute
  HELM_SERVICE_NAME: vault-attribute

jobs:
  code-quality-check:
    uses: ...

  test-and-code-coverage:
    uses: ...

  containerise:
    uses: ...

  deploy-dev:
    uses: glimspe-deploy-workflow
    needs: containerise
    with:
      AWS_REGION: eu-west-1
      CLUSTER_NAME: gpsk-alpha-euw1-eks
```

2022-01-25 14:48 UTC, tim-hm requested changes
Nearly there!!

2022-01-25 14:48 UTC, tim-hm commented on .github/workflows/containerise.yml
> +          cache: gradle
- please bump the name to JDK 17
- the jdk 17 distribution has changed from adopt to temurin

2022-01-25 14:48 UTC, tim-hm commented on .github/workflows/code-quality-check.yml
> +          cache: gradle
Same comment elsewhere about jdk 17

2022-01-25 14:48 UTC, tim-hm commented on .github/workflows/code-quality-check.yml
> +        run: ./gradlew classes detekt
Do we need to run `classes` before `detekt`?

2022-01-25 14:48 UTC, tim-hm commented on .github/workflows/code-quality-check.yml
> +        run: ./gradlew sonarqube -Dkotest.tags="!Integration"
We should be able to run integration tests now 🤞

2022-01-25 14:48 UTC, tim-hm commented on .github/workflows/code-quality-check.yml
> +          echo "COMMONS_BRANCH=$COMMONS_BRANCH" >> $GITHUB_ENV
Anyway to extract this step into a separate workflow as its used quite regularly?

2022-01-25 14:48 UTC, tim-hm commented on .github/workflows/containerise.yml
> +          aws-region: eu-west-1
Region should come from an env var 🙏

2022-01-25 14:48 UTC, tim-hm commented on .github/workflows/test-and-code-coverage.yml
> +          cache: gradle
JDK 17 comment

2022-01-25 15:23 UTC, samueldobbie commented on .github/workflows/code-quality-check.yml
> +          echo "COMMONS_BRANCH=$COMMONS_BRANCH" >> $GITHUB_ENV
Yeah, we can have something like the below, although we'd have to move the workflow call to occur within the service (a called workflow can't call another).

```yaml
name: checkout-service

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      TARGET_BRANCH:
        required: true
        type: string

    secrets:
      GH_PAT:
        required: true

jobs:
  checkout-branch:
    name: Checkout service @ target branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling service
        uses: actions/checkout@v2
        with:
          path: ${{ inputs.SERVICE_NAME }}

      - name: Extract branch name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch

      - name: Check for matching branch
        uses: octokit/request-action@v2.x
        id: get-branch-active
        with:
          route: GET /repos/glimpse-protocol/${{ inputs.SERVICE_NAME }}/branches/${{ steps.extract-branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        continue-on-error: true

      - name: Determine which ${{ inputs.SERVICE_NAME }} branch to checkout
        run: |
          if [[ ${{ steps.extract-branch.outputs.branch }} == "main" ]]; then
            ACTIVE_BRANCH=main
          elif [[ '${{ steps.get-branch-active.outputs.status }}' = '200' ]]; then
            ACTIVE_BRANCH="${{ steps.extract-branch.outputs.branch }}"
          else
            ACTIVE_BRANCH=dev
          fi

          echo "${{ inputs.SERVICE_NAME }} branch to checkout: $ACTIVE_BRANCH"
          echo "ACTIVE_BRANCH=$ACTIVE_BRANCH" >> $GITHUB_ENV

      - name: Checkout ${{ inputs.SERVICE_NAME }}
        uses: actions/checkout@v2
        with:
          repository: glimpse-protocol/${{ inputs.SERVICE_NAME }}
          ref: ${{ env.ACTIVE_BRANCH }}
          token: ${{ secrets.GH_PAT }}
          path: ${{ inputs.SERVICE_NAME }}
```

2022-01-25 15:28 UTC, tim-hm commented on .github/workflows/code-quality-check.yml
> +          echo "COMMONS_BRANCH=$COMMONS_BRANCH" >> $GITHUB_ENV
Hmm .. so what does that look like inside the service's workflow file then?

2022-01-25 15:58 UTC, tim-hm commented on .github/workflows/code-quality-check.yml
> +          echo "COMMONS_BRANCH=$COMMONS_BRANCH" >> $GITHUB_ENV
okay that makes sense ... lets pause that and circle back once its all togehter 👍

2022-01-25 15:58 UTC, tim-hm approved these changes

2022-01-27 16:41 UTC, tim-hm requested changes
Two amendments please and then go ahead and merge without another review 🙏

2022-01-27 16:41 UTC, tim-hm commented on .github/workflows/deploy-to-aws.yml
> +          echo $(aws sts get-caller-identity)
is this still needed?

2022-01-27 16:41 UTC, tim-hm commented on .github/workflows/containerise.yml
> +        required: true
Can we move these into input and then env vars from the calling action please?

2022-01-27 16:51 UTC, merged